### ISSUE TITLE
Ensure RubyTest works with Sublime Text 3

### ISSUE THREAD

**Issue by gja** [maltize/sublime-text-2-ruby-tests#148]
Lots of new changes in the ChangeLog:

http://www.sublimetext.com/3

The only one that looks urgent is the fact that begin_edit and end_edit are missing.

API: Upgraded from Python 2.6 to Python 3.3
API: Plugins run out-of-process
API: Plugin API is now threadsafe
API: Some API events are now run asynchronously
API: begin_edit() / end_edit() are no longer accessible
API: Projects are exposed to the API
API: Added window.settings() and window.template_settings()
API: show_quick_panel accepts an on_highlighted callback

**Comment by mariusbutuc** [comment]
Any update on RubyTest working with Sublime Text 3?

**Comment by danbartlett** [comment]
Any hints on how to get this working with ST3?

**Comment by jancel** [comment]
Any updates?

**Comment by ccurtisj** [comment]
Bump - any update on scratch support?

**Comment by apolzon** [comment]
This was working for me prior to the update that installed today. Getting the same errors as posted above:

```
Traceback (most recent call last):
  File "run_ruby_test in /Users/apolzon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 60, in copy_stuff
  File "run_ruby_test in /Users/apolzon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 49, in append
TypeError: begin_edit() missing 2 required positional arguments: 'edit_token' and 'cmd'

```

**Comment by nicosantangelo** [comment]
Hey @apolzon, I think the fork I posted a few comments up ( [here](https://github.com/maltize/sublime-text-2-ruby-tests/issues/148#issuecomment-32079942) ) continues to work.

I'm no longer using Ruby and don't intend to keep it as an _official fork_ or anything. But seeing that this repo didn't have many updates lately, it might be a good replacement for anyone who may want to use it.
