### ISSUE TITLE
No output when using scratch on MacOS 10.7.5

### ISSUE THREAD

**Issue by A5308Y** [maltize/sublime-text-2-ruby-tests#209]
I can run the tests fine without using scratch. When I enable "ruby_use_scratch" : true and run a test a new tab titled "Test Results" opens that is empty. 
When I open the test panel at the bottom manually I can see that the the output of my test still arrives there.

Some hopefully helpful things I noticed:
- The background is black, so I guess it's recognized as the right buffer somewhere...
- The output in the panel is not colorized. It is when not trying to use scratch.
- The second time a run a test the same "Test Results" tab becomes focused (No new tab) and the manullay opened test panel gets closed.

I'm unsure if I need to install scratch? I couldn't find sublime package named like that. Or anything on the internet (apart from manuals for doing all sorts of things from scratch)

I'm using sublime 3 Build 3047.

My RubyTest user settings:
{
  "check_for_rvm": true,
  "run_rspec_command": "zeus rspec {relative_path}",
  "run_single_rspec_command": "zeus rspec {relative_path}:{line_number}",
  "ruby_use_scratch" : true
}
## Trace:

Running /Users/<username>/.rvm/bin/rvm-auto-ruby -S zeus rspec spec/models/admin_spec.rb:12
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "run_ruby_test in /Users/<username>/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 341, in run
  File "run_ruby_test in /Users/<username>/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 207, in run_shell_command
  File "run_ruby_test in /Users/<username>/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 212, in display_results
  File "run_ruby_test in /Users/<username>/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 39, in display_results
  File "run_ruby_test in /Users/<username>/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 49, in append
TypeError: begin_edit() missing 2 required positional arguments: 'edit_token' and 'cmd'
Unable to open <path>/spec/models/Test Results
reloading Packages/User/RubyTest.last-run
Traceback (most recent call last):
  File "run_ruby_test in /Users/<username>/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 60, in copy_stuff
  File "run_ruby_test in /Users/<username>/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 49, in append
TypeError: begin_edit() missing 2 required positional arguments: 'edit_token' and 'cmd'

---

Thanks!
Andy

**Comment by joowh85** [comment]
It's not only Mac OS
In the Ubuntu doesn't work too
