### ISSUE TITLE
Exceptions in find_project_root [OS X Mavericks]

### ISSUE THREAD

**Issue by jonbrenner** [maltize/sublime-text-2-ruby-tests#240]
startup, version: 3065 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/jon/Library/Application Support/Sublime Text 3/Packages
state path: /Users/jon/Library/Application Support/Sublime Text 3/Local
hardware concurrency: 8
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages
found 7 files for base name Default.sublime-keymap
found 2 files for base name Default.sublime-mousemap
found 5 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
wrote startup cache, added files: 47 orphaned files: 0 total files: 188 cache hits: 141
pre session restore time: 3.70795
using gpu buffer for window
using gamma: 2 (err: 6.9282)
first paint time: 3.7642
startup time: 3.78484
launching: /Applications/Sublime Text.app/Contents/MacOS/plugin_host
loaded 906 snippets
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ElasticTabstops.edit
reloading plugin ElasticTabstops.elastic_tabstops
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Package Control.Package Control
reloading plugin RSpec.OpenRSpecFile
reloading plugin RSpec.RSpecCreateModule
reloading plugin RSpec.RSpecDetectFileType
reloading plugin RSpec.shared
reloading plugin RubyTest.run_ruby_test
reloading plugin Sublimerge Pro.Sublimerge
plugins loaded
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 440, in is_enabled_
    ret = self.is_enabled()
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 335, in is_enabled
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 307, in file_type
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 141, in load_config
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 163, in bundler_support
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 230, in find_project_root
AttributeError: 'AnonymousFile' object has no attribute 'partition_folder'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 440, in is_enabled_
    ret = self.is_enabled()
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 335, in is_enabled
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 307, in file_type
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 141, in load_config
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 163, in bundler_support
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 230, in find_project_root
AttributeError: 'AnonymousFile' object has no attribute 'partition_folder'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 440, in is_enabled_
    ret = self.is_enabled()
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 345, in is_enabled
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 307, in file_type
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 141, in load_config
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 163, in bundler_support
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 230, in find_project_root
AttributeError: 'AnonymousFile' object has no attribute 'partition_folder'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 440, in is_enabled_
    ret = self.is_enabled()
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 345, in is_enabled
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 307, in file_type
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 141, in load_config
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 163, in bundler_support
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 230, in find_project_root
AttributeError: 'AnonymousFile' object has no attribute 'partition_folder'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 440, in is_enabled_
    ret = self.is_enabled()
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 369, in is_enabled
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 307, in file_type
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 141, in load_config
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 163, in bundler_support
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 230, in find_project_root
AttributeError: 'AnonymousFile' object has no attribute 'partition_folder'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 440, in is_enabled_
    ret = self.is_enabled()
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 369, in is_enabled
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 307, in file_type
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 141, in load_config
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 163, in bundler_support
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 230, in find_project_root
AttributeError: 'AnonymousFile' object has no attribute 'partition_folder'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 438, in is_enabled_
    ret = self.is_enabled(**args)
TypeError: is_enabled() got an unexpected keyword argument 'split_view'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 442, in is_enabled_
    ret = self.is_enabled()
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 380, in is_enabled
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 307, in file_type
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 141, in load_config
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 163, in bundler_support
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 230, in find_project_root
AttributeError: 'AnonymousFile' object has no attribute 'partition_folder'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 438, in is_enabled_
    ret = self.is_enabled(**args)
TypeError: is_enabled() got an unexpected keyword argument 'split_view'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 442, in is_enabled_
    ret = self.is_enabled()
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 380, in is_enabled
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 307, in file_type
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 141, in load_config
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 163, in bundler_support
  File "run_ruby_test in /Users/jon/Library/Application Support/Sublime Text 3/Installed Packages/RubyTest.sublime-package", line 230, in find_project_root
AttributeError: 'AnonymousFile' object has no attribute 'partition_folder'
Package Control: Skipping automatic upgrade, last run at 2014-10-20 17:28:53, next run at 2014-10-20 18:28:53 or after

**Comment by benjaminwood** [comment]
I'm also having this problem on ST3 & Yosemite.
